name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile-metrics.svg

          output_action: gist
          committer_gist: ${{ secrets.GIST }}

          base: header

          config_order: base.header, isocalendar_contributions_graph, isocalendar, languages

          # 1. Isometric commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # 2. Most used languages
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_details: bytes, percentage
          plugin_languages_limit: 8
